//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SETUNA.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SETUNA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   SetunaConfig.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigFile {
            get {
                return ResourceManager.GetString("ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Bmp {
            get {
                object obj = ResourceManager.GetObject("Icon_Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Close {
            get {
                object obj = ResourceManager.GetObject("Icon_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Compact {
            get {
                object obj = ResourceManager.GetObject("Icon_Compact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Copy {
            get {
                object obj = ResourceManager.GetObject("Icon_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Frame {
            get {
                object obj = ResourceManager.GetObject("Icon_Frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Jpeg {
            get {
                object obj = ResourceManager.GetObject("Icon_Jpeg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Move {
            get {
                object obj = ResourceManager.GetObject("Icon_Move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Opacoty {
            get {
                object obj = ResourceManager.GetObject("Icon_Opacoty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Paste {
            get {
                object obj = ResourceManager.GetObject("Icon_Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Picasa {
            get {
                object obj = ResourceManager.GetObject("Icon_Picasa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Png {
            get {
                object obj = ResourceManager.GetObject("Icon_Png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Rotate {
            get {
                object obj = ResourceManager.GetObject("Icon_Rotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Scale {
            get {
                object obj = ResourceManager.GetObject("Icon_Scale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Trim {
            get {
                object obj = ResourceManager.GetObject("Icon_Trim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fliphorizontally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label10 {
            get {
                return ResourceManager.GetString("label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the type of border for the reference image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label100 {
            get {
                return ResourceManager.GetString("label100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3D border に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label101 {
            get {
                return ResourceManager.GetString("label101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monochrome border に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label102 {
            get {
                return ResourceManager.GetString("label102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label103 {
            get {
                return ResourceManager.GetString("label103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the reference image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label104 {
            get {
                return ResourceManager.GetString("label104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the reference image up, down, left, or right. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label105 {
            get {
                return ResourceManager.GetString("label105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label106 {
            get {
                return ResourceManager.GetString("label106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label107 {
            get {
                return ResourceManager.GetString("label107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label108 {
            get {
                return ResourceManager.GetString("label108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label109 {
            get {
                return ResourceManager.GetString("label109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enlarge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label11 {
            get {
                return ResourceManager.GetString("label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label110 {
            get {
                return ResourceManager.GetString("label110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set opaque reference image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label111 {
            get {
                return ResourceManager.GetString("label111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label112 {
            get {
                return ResourceManager.GetString("label112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can draw directly on the reference image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label113 {
            get {
                return ResourceManager.GetString("label113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste from clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label114 {
            get {
                return ResourceManager.GetString("label114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use the image from clipboard as a reference image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label115 {
            get {
                return ResourceManager.GetString("label115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Album uploaded with SETUNA. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label116 {
            get {
                return ResourceManager.GetString("label116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload to Picasa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label117 {
            get {
                return ResourceManager.GetString("label117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload the reference image to Picasa web album. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label118 {
            get {
                return ResourceManager.GetString("label118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label119 {
            get {
                return ResourceManager.GetString("label119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enlarge(fine-tune) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label12 {
            get {
                return ResourceManager.GetString("label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause within the specified time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label120 {
            get {
                return ResourceManager.GetString("label120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grayscale level inversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label121 {
            get {
                return ResourceManager.GetString("label121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perform inversion of grayscale levels. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label122 {
            get {
                return ResourceManager.GetString("label122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label123 {
            get {
                return ResourceManager.GetString("label123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can delete unnecessary parts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label124 {
            get {
                return ResourceManager.GetString("label124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text layer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label125 {
            get {
                return ResourceManager.GetString("label125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shrink the size of the reference image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label126 {
            get {
                return ResourceManager.GetString("label126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shrink the size of the reference image.\nSubsequent automatic operations will not be used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label127 {
            get {
                return ResourceManager.GetString("label127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label128 {
            get {
                return ResourceManager.GetString("label128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy the reference image as an image to the clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label129 {
            get {
                return ResourceManager.GetString("label129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reduce に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label13 {
            get {
                return ResourceManager.GetString("label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label130 {
            get {
                return ResourceManager.GetString("label130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close the reference image.\nSubsequent automatic operations will not be used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label131 {
            get {
                return ResourceManager.GetString("label131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reduce(fine-tune) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label14 {
            get {
                return ResourceManager.GetString("label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Official version (address is invalid) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label149 {
            get {
                return ResourceManager.GetString("label149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increaseopacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label15 {
            get {
                return ResourceManager.GetString("label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimized version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label150 {
            get {
                return ResourceManager.GetString("label150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Related editing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label151 {
            get {
                return ResourceManager.GetString("label151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETUNA general settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label152 {
            get {
                return ResourceManager.GetString("label152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perform settings related to cropping に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label153 {
            get {
                return ResourceManager.GetString("label153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perform general settings for reference images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label154 {
            get {
                return ResourceManager.GetString("label154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create an automatic operation composed of multiple automatic operations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label155 {
            get {
                return ResourceManager.GetString("label155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the menu when right-clicking on a reference image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label156 {
            get {
                return ResourceManager.GetString("label156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse cursor style settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label157 {
            get {
                return ResourceManager.GetString("label157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new automatic operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label158 {
            get {
                return ResourceManager.GetString("label158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize the setting content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label159 {
            get {
                return ResourceManager.GetString("label159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increaseopacity(fine-tune) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label16 {
            get {
                return ResourceManager.GetString("label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decreaseopacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label17 {
            get {
                return ResourceManager.GetString("label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decreaseopacity(fine-tune) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label18 {
            get {
                return ResourceManager.GetString("label18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moveup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label19 {
            get {
                return ResourceManager.GetString("label19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy(withborder) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moveup(fine-tune) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label20 {
            get {
                return ResourceManager.GetString("label20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movedown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label21 {
            get {
                return ResourceManager.GetString("label21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movedown(fine-tune) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label22 {
            get {
                return ResourceManager.GetString("label22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moveleft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label23 {
            get {
                return ResourceManager.GetString("label23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moveleft(fine-tune) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label24 {
            get {
                return ResourceManager.GetString("label24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moveright に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label25 {
            get {
                return ResourceManager.GetString("label25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moveright(fine-tune) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label26 {
            get {
                return ResourceManager.GetString("label26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaleto50% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label27 {
            get {
                return ResourceManager.GetString("label27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaleto60% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label28 {
            get {
                return ResourceManager.GetString("label28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaleto70% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label29 {
            get {
                return ResourceManager.GetString("label29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaleto80% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label30 {
            get {
                return ResourceManager.GetString("label30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaleto90% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label31 {
            get {
                return ResourceManager.GetString("label31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaleto100% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label32 {
            get {
                return ResourceManager.GetString("label32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scaleto150% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label33 {
            get {
                return ResourceManager.GetString("label33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3Dborder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label34 {
            get {
                return ResourceManager.GetString("label34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monochromeborder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label35 {
            get {
                return ResourceManager.GetString("label35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label36 {
            get {
                return ResourceManager.GetString("label36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Noborder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label37 {
            get {
                return ResourceManager.GetString("label37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label38 {
            get {
                return ResourceManager.GetString("label38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basicautomaticoperation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label39 {
            get {
                return ResourceManager.GetString("label39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut(withborder) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shrink に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label40 {
            get {
                return ResourceManager.GetString("label40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label41 {
            get {
                return ResourceManager.GetString("label41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   recycle bin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label50 {
            get {
                return ResourceManager.GetString("label50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   reference image list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label51 {
            get {
                return ResourceManager.GetString("label51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make a reference map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label52 {
            get {
                return ResourceManager.GetString("label52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label53 {
            get {
                return ResourceManager.GetString("label53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VersionInformation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label54 {
            get {
                return ResourceManager.GetString("label54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExitSETUNA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label55 {
            get {
                return ResourceManager.GetString("label55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HideAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label56 {
            get {
                return ResourceManager.GetString("label56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label57 {
            get {
                return ResourceManager.GetString("label57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label58 {
            get {
                return ResourceManager.GetString("label58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EmptyRecycleBin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label59 {
            get {
                return ResourceManager.GetString("label59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CloseAllScreenshots に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label60 {
            get {
                return ResourceManager.GetString("label60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CloseAllScreenshots? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label61 {
            get {
                return ResourceManager.GetString("label61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label62 {
            get {
                return ResourceManager.GetString("label62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label63 {
            get {
                return ResourceManager.GetString("label63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PasteScreenshotfromClipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label64 {
            get {
                return ResourceManager.GetString("label64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label65 {
            get {
                return ResourceManager.GetString("label65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unabletosaveconfigurationfile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label66 {
            get {
                return ResourceManager.GetString("label66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unabletosaveconfigurationfile.Usingdefaultsettings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label67 {
            get {
                return ResourceManager.GetString("label67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETUNAisalreadyrunninginadifferentversion. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label68 {
            get {
                return ResourceManager.GetString("label68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -Commandlineparameters-------------------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label69 {
            get {
                return ResourceManager.GetString("label69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save(withborder) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Location] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label70 {
            get {
                return ResourceManager.GetString("label70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalidfoldername. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label71 {
            get {
                return ResourceManager.GetString("label71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nofilenamespecified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label72 {
            get {
                return ResourceManager.GetString("label72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalidfilename. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label73 {
            get {
                return ResourceManager.GetString("label73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotateandflip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label74 {
            get {
                return ResourceManager.GetString("label74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Referenceimageforrotationandflipping. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label75 {
            get {
                return ResourceManager.GetString("label75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Referenceimageforscaling. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label76 {
            get {
                return ResourceManager.GetString("label76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Referenceimageforscalingdown/up. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label77 {
            get {
                return ResourceManager.GetString("label77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Originalsize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label78 {
            get {
                return ResourceManager.GetString("label78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %Fixed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label79 {
            get {
                return ResourceManager.GetString("label79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate90degrees に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label8 {
            get {
                return ResourceManager.GetString("label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %Enlarged に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label80 {
            get {
                return ResourceManager.GetString("label80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %Reduced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label81 {
            get {
                return ResourceManager.GetString("label81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windowize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label82 {
            get {
                return ResourceManager.GetString("label82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Addwindowbordertothereferenceimage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label83 {
            get {
                return ResourceManager.GetString("label83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label84 {
            get {
                return ResourceManager.GetString("label84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label85 {
            get {
                return ResourceManager.GetString("label85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as BMP format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label86 {
            get {
                return ResourceManager.GetString("label86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the reference image as BMP format image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label87 {
            get {
                return ResourceManager.GetString("label87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitmap format (.bmp)|.bmp|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label88 {
            get {
                return ResourceManager.GetString("label88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as JPEG format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label89 {
            get {
                return ResourceManager.GetString("label89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flipvertically に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the reference image as JPEG format image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label90 {
            get {
                return ResourceManager.GetString("label90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Jpeg format (.jpg)|.jpg|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label91 {
            get {
                return ResourceManager.GetString("label91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as PNG format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label92 {
            get {
                return ResourceManager.GetString("label92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the reference image as PNG format image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label93 {
            get {
                return ResourceManager.GetString("label93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Png format (.png)|.png|All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label94 {
            get {
                return ResourceManager.GetString("label94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label95 {
            get {
                return ResourceManager.GetString("label95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File with the same name already exists. Overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label96 {
            get {
                return ResourceManager.GetString("label96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save the image because no suitable encoder was found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label97 {
            get {
                return ResourceManager.GetString("label97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label98 {
            get {
                return ResourceManager.GetString("label98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Border に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label99 {
            get {
                return ResourceManager.GetString("label99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap OptionBG {
            get {
                object obj = ResourceManager.GetObject("OptionBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap pi_erase {
            get {
                object obj = ResourceManager.GetObject("pi_erase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap pi_pen {
            get {
                object obj = ResourceManager.GetObject("pi_pen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap pi_text {
            get {
                object obj = ResourceManager.GetObject("pi_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PicasaLogo {
            get {
                object obj = ResourceManager.GetObject("PicasaLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
